apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    id: app
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      id: app
  template:
    metadata:
      labels:
        id: app
    spec:
      containers:
      - image: verces/k8s-hpa:lastest
        name: app
        imagePullPolicy: Always
        resources:
          request:
            cpu: "250m"
          limit:
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    id: lb
  name: lb
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    id: app
  type: LoadBalancer