apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cloudhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 2
  maxReplicas: 40
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 70
      type: Resource
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    id: app
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      id: app
  template:
    metadata:
      labels:
        id: app
    spec:
      containers:
      - image: verces/k8s-hpa:lastest
        name: app
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    id: lb
  name: lb
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    id: app
  type: LoadBalancer